# Generated by Django 2.2.3 on 2019-07-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comers',
            old_name='attend_status',
            new_name='status',
        ),
    ]
