# Generated by Django 2.2.3 on 2019-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190727_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='comers',
            name='late_time',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
