# Generated by Django 2.2.3 on 2019-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_comers_late_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comers',
            name='late_time',
            field=models.IntegerField(max_length=100),
        ),
    ]
